### ISSUE TITLE
自行训练的疑惑

### ISSUE THREAD

**Issue by kagg886** [BeigeInk/lyt_image#2]
请问如果拥有更多数量的龙图
在调参方面有要求吗

**Comment by BeigeInk** [comment]
没有其他参数的建议，可以自行尝试
此外，网络并不是VGG11只是我随手改的，我的建议是可以尝试增加网络层数或者选用其他性能更优的网络结构

**Comment by kagg886** [comment]
> 没有其他参数的建议，可以自行尝试
> 此外，网络并不是VGG11只是我随手改的，我的建议是可以尝试增加网络层数或者选用其他性能更优的网络结构

我在这方面是一个noob(

顺带一提问一下，ult文件夹放什么样的图片
这边没看到ult文件夹应该放什么图片，而我如果不放图片的话，训出的模型根本就不好用x

**Comment by BeigeInk** [comment]
ult是放非龙图的图片，这代码我本来是打算用在QQ群里的，所以我ult使用的是qq的其他表情包，qq的表情包可以直接在自己电脑里面的qq数据文件夹里面提取

**Comment by kagg886** [comment]
> ult是放非龙图的图片，这代码我本来是打算用在QQ群里的，所以我ult使用的是qq的其他表情包，qq的表情包可以直接在自己电脑里面的qq数据文件夹里面提取

数据量应该和龙图持平吗？

还有一个问题就是

如果我有三个batch，每个batch分别500张图片，模型代码需要什么改动呢(((

~~别喷，我是真菜，呜呜呜~~

**Comment by BeigeInk** [comment]
> > ult是放非龙图的图片，这代码我本来是打算用在QQ群里的，所以我ult使用的是qq的其他表情包，qq的表情包可以直接在自己电脑里面的qq数据文件夹里面提取
> 
> 数据量应该和龙图持平吗？
> 
> 还有一个问题就是
> 
> 如果我有三个batch，每个batch分别500张图片，模型代码需要什么改动呢(((
> 
> ~别喷，我是真菜，呜呜呜~

A_1:建议持平

A_2:我没有其他建议，根据实际来设置训练时候的超参数和模型层数，建议你提前了解一下这些超参数的具体含义，以更好的辅助你做好模型
